export const HANDLE_NAME_CHANGE = 'HANDLE_NAME_CHANGE';
export const HANDLE_START_GAME = 'HANDLE_START_GAME';

export const HANDLE_CARDS_SHUFFLE = 'HANDLE_CARDS_SHUFFLE';

export const HANDLE_BET_VALUE = 'HANDLE_BET_VALUE';

export const HANDLE_RIGHT_GUESS = 'HANDLE_RIGHT_GUESS';
export const HANDLE_WRONG_GUESS = 'HANDLE_WRONG_GUESS';
export const HANDLE_TIE = 'HANDLE_TIE';
export const HANDLE_RESET_GAME = 'HANDLE_RESET_GAME';
